## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

#### 교과목명 : 분석라이브러리 활용

- 평가일 : 22.7.10
- 성명 : 김영선
- 점수 : 89

### Q1. 표준정규분포 기반의 2행 3열 배열을 랜덤하게 생성하여 크기, 자료형, 차원을 출력하세요.

In [1]:
import numpy as np
a = np.random.randn(2,3)
print(a.shape)
print(a.dtype)
print(a.ndim)

(2, 3)
float64
2


### Q2. arange(), reshape() 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.
[0 1 2 3 4 5 6 7 8 9]  

[[0 1 2 3 4]  
 [5 6 7 8 9]]  
 
[[[0 1 2 3 4]  
  [5 6 7 8 9]]]

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
a.reshape(-1,2,5)

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

### Q3. 1 ~ 100 까지 배열에서 3과 7의 공배수인 것만을 출력하세요.

In [6]:
a = np.arange(1,101)
ar = a[(a%3==0)&(a%7==0)]
ar

array([21, 42, 63, 84])

### Q4. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.(reshape() 사용)

[[[ 0  1  2  3  4]  
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]  
   [15 16 17 18 19]]

 [[20 21 22 23 24]  
   [25 26 27 28 29]]]

In [7]:
a=np.arange(30).reshape(3,2,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [8]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Q5. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
arr2d = np.arange(1,10).reshape(3,3)

[3, 6]  

[[1, 2],  
[4, 5]]

[[1, 2, 3]  
[4, 5, 6]]

In [9]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2d[:2,2]

array([3, 6])

In [11]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [12]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

### Q6. zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [13]:
a = np.arange(1,10).reshape(3,3)
b = np.zeros_like(a)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
c = np.ones_like(a)
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
d = np.full_like(a,7)
d

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### Q7. 10 ~ 20 사이의 정수 난수로 10행 5열 2차원 배열을 생성하고 저장한 후 다시 불러내서 출력하세요.

In [16]:
a = np.random.randint(10,21,size=(10,5))
a

array([[19, 17, 11, 19, 19],
       [12, 14, 11, 19, 10],
       [20, 15, 16, 14, 20],
       [20, 10, 17, 13, 14],
       [13, 14, 17, 11, 13],
       [15, 11, 15, 15, 12],
       [17, 13, 10, 16, 14],
       [12, 19, 17, 14, 20],
       [19, 14, 11, 14, 17],
       [13, 17, 15, 15, 17]])

In [17]:
np.save('ar_test',a)
np.load('ar_test.npy')

array([[19, 17, 11, 19, 19],
       [12, 14, 11, 19, 10],
       [20, 15, 16, 14, 20],
       [20, 10, 17, 13, 14],
       [13, 14, 17, 11, 13],
       [15, 11, 15, 15, 12],
       [17, 13, 10, 16, 14],
       [12, 19, 17, 14, 20],
       [19, 14, 11, 14, 17],
       [13, 17, 15, 15, 17]])

### Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived'외에 모든 칼럼을 포함한 df_x를 산출한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다. 

In [18]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [19]:
df_x = df[['pclass','sex','age','sibsp','parch','fare','embarked','class','who','adult_male','deck','embark_town','alive','alone']]
df_x.head()
df_x.to_pickle('dataset/df_x.pkl')

In [20]:
df_x = pd.read_pickle('dataset/df_x.pkl')
df_x.head()

pclass     sex   age  sibsp  parch     fare embarked  class    who  \
0       3    male  22.0      1      0   7.2500        S  Third    man   
1       1  female  38.0      1      0  71.2833        C  First  woman   
2       3  female  26.0      0      0   7.9250        S  Third  woman   
3       1  female  35.0      1      0  53.1000        S  First  woman   
4       3    male  35.0      0      0   8.0500        S  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

### Q9. df = sns.load_dataset('titanic')로 불러와서 deck 열에서 NaN 갯수를 계산하세요.

In [21]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [22]:
df.deck.isnull().sum()

688

### Q10. Q9의 df에서 각 칼럼별 null 개수와 df 전체의 null 개수를 구하세요.

In [23]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [24]:
df.isnull().sum().sum()

869

### 아래 tdf 데이터프레임에서 Q11 ~ Q12 작업을 수행하세요.

In [25]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

survived     sex   age  class
0         0    male  22.0  Third
1         1  female  38.0  First
2         1  female  26.0  Third
3         1  female  35.0  First
4         0    male  35.0  Third

### Q11. age를 7개 카테고리로 구분하는 새로운 칼럼 'cat_age'를 생성하여 출력하세요. 단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 age 칼럼에 매핑하여 결과를 tdf1에 저장하고 출력하세요.

[카테고리]  
age <= 5: cat = 'Baby'  
age <= 12: cat = 'Child'  
age <= 18: cat = 'Teenager'  
age <= 25: cat = 'Student'  
age <= 60: cat = 'Adult'  
age > 60 : cat = 'Elderly'

In [26]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

survived     sex   age  class
0         0    male  22.0  Third
1         1  female  38.0  First
2         1  female  26.0  Third
3         1  female  35.0  First
4         0    male  35.0  Third

In [27]:
def cat_age(x):
    cat = ''
    if x <= 5:
        cat = 'Baby'
    elif x <= 12:
        cat = 'Child'
    elif x <= 18:
        cat = 'Teenager'
    elif x <= 25:
        cat = 'Student'
    elif x <= 60:
        cat = 'Adult'
    else :
        cat = 'Elderly'

    return cat

In [28]:
import warnings
warnings.filterwarnings('ignore')

In [29]:
tdf1 = tdf.copy()
tdf1['cat_age'] = tdf['age'].apply(cat_age)
tdf1.head()

survived     sex   age  class  cat_age
0         0    male  22.0  Third  Student
1         1  female  38.0  First    Adult
2         1  female  26.0  Third    Adult
3         1  female  35.0  First    Adult
4         0    male  35.0  Third    Adult

### Q12.  tdf1의 sex, class 칼럼을 '_'으로 연결한 'sc'칼럼을 추가한 후 아래와 같이 출력하세요.



In [30]:
tdf1['sc']=tdf1[['sex','class']].agg('_'.join,axis=1)
tdf1.head()

survived     sex   age  class  cat_age            sc
0         0    male  22.0  Third  Student    male_Third
1         1  female  38.0  First    Adult  female_First
2         1  female  26.0  Third    Adult  female_Third
3         1  female  35.0  First    Adult  female_First
4         0    male  35.0  Third    Adult    male_Third

### Q13. join() 메소드는 두 데이터프레임의 행 인덱스를 기준으로 결합한다. 2개의 주식데이터를 가져와서 join() 메소드로 아래와 같이 결합한 후 다음 사항을 수행하세요.
- df1과 df2의 교집합만 출력되도록 결합하여 df3에 저장하고 출력
- df3에서 중복된 칼럼을 삭제한 후 블린 인덱싱을 이용하여 eps가 3000 보다 적거나 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df4 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)

In [31]:
import pandas as pd
df1 = pd.read_excel('./dataset/stock price.xlsx', index_col='id')
df2 = pd.read_excel('./dataset/stock valuation.xlsx', index_col='id')

In [32]:
df3 = df1.join(df2,how='inner')
df3.head()

stock_name          value   price    name           eps     bps  \
id                                                                       
130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068   
139480        이마트  239230.833333  254500     이마트  18268.166667  295780   
145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090   
185750        종근당   40293.666667  100500     종근당   3990.333333   40684   
204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335   

              per       pbr  
id                           
130960  15.695091  1.829178  
139480  13.931338  0.860437  
145990  14.283226  0.758627  
185750  25.185866  2.470259  
204210  40.802348  0.651359

In [33]:
df3.T.duplicated()

stock_name    False
value         False
price         False
name           True
eps           False
bps           False
per           False
pbr           False
dtype: bool

In [34]:
~df3.T.duplicated()

stock_name     True
value          True
price          True
name          False
eps            True
bps            True
per            True
pbr            True
dtype: bool

In [35]:
df3.loc[:,~df3.T.duplicated()]

stock_name          value   price           eps     bps        per  \
id                                                                          
130960     CJ E&M   58540.666667   98900   6301.333333   54068  15.695091   
139480        이마트  239230.833333  254500  18268.166667  295780  13.931338   
145990        삼양사   82750.000000   82000   5741.000000  108090  14.283226   
185750        종근당   40293.666667  100500   3990.333333   40684  25.185866   
204210     모두투어리츠    3093.333333    3475     85.166667    5335  40.802348   

             pbr  
id                
130960  1.829178  
139480  0.860437  
145990  0.758627  
185750  2.470259  
204210  0.651359

In [36]:
df4 = df3[(df3['eps']<3000)|(df3['stock_name']=='이마트')]
df4

stock_name          value   price    name           eps     bps  \
id                                                                       
139480        이마트  239230.833333  254500     이마트  18268.166667  295780   
204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335   

              per       pbr  
id                           
139480  13.931338  0.860437  
204210  40.802348  0.651359

### Q14. 배열 a에 대하여 3차원 자리에 2차원을 2차원 자리에 1차원을 1차원 자리에 3차원을 넣어서 변환하여 출력하세요

In [37]:
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 



In [38]:
b = np.transpose(a,(1,2,0))
print(b,b.shape)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


### Q15. 'mpg'를 'kpl' 로 환산하여 새로운 열을 생성하고 반올림하여 소수점 아래 둘째 자리까지 처음 5개행을 출력하세요.

In [39]:
# read_csv() 함수로 df 생성
import pandas as pd
auto_df = pd.read_csv('./dataset/auto-mpg.csv')
# 열 이름을 지정
auto_df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
print(auto_df.head(3)) 


    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  


In [40]:
mpg_to_kpl = 1.60934 / 3.78541
mpg_to_kpl

0.42514285110463595

In [41]:
auto_df['kpl'] = round(auto_df['mpg']*mpg_to_kpl,2)
auto_df[['mpg','kpl']].head()

mpg   kpl
0  18.0  7.65
1  15.0  6.38
2  18.0  7.65
3  16.0  6.80
4  17.0  7.23

### Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 datetime64 자료형으로 변환한 후에 년, 월, 일로 분리하고 year를 인덱스로 셋팅하여 출력하세요.

In [42]:
df = pd.read_csv('./dataset/stock-data.csv')
df.head()

Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [43]:
import time

df['Date'] = df['Date'].to_datetime(df['Date'])
df['year'] = df['Date'].dt.year
df['month']=df['Date'].dt.month
df['day'] = df['Date'].dt.day

df.set_index('year',inplace=True)
df.head()

AttributeError: 'Series' object has no attribute 'to_datetime'

### Q17. titanic 데이터셋(titanic = sns.load_dataset('titanic'))에서 5개 열을 선택해서 class열을 기준으로 그룹화를 수행한 후 아래와 같이 출력하였다. 다음 사항을 출력하세요.
5개 열 : ['age','sex', 'class', 'fare', 'survived']  
- 그룹별 평균 출력
- 그룹별 최대값 출력

In [44]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [45]:
df1= df[['age','sex','class','fare','survived']]
df1.head()

age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [46]:
grouped = df1.groupby('class')

In [47]:
grouped.max()

age   sex      fare  survived
class                                 
First   80.0  male  512.3292         1
Second  70.0  male   73.5000         1
Third   74.0  male   69.5500         1

In [49]:
grouped.mean()

age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

### Q18. titanic 데이터셋에서 'Third'그룹만을 선택해서 group3 이름으로 저장하고 통계요약표를 출력하세요.

In [50]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [51]:
grouped = df.groupby('class')

In [52]:
group3 = grouped.get_group('Third')
group3.describe()

survived  pclass         age       sibsp       parch        fare
count  491.000000   491.0  355.000000  491.000000  491.000000  491.000000
mean     0.242363     3.0   25.140620    0.615071    0.393075   13.675550
std      0.428949     0.0   12.495398    1.374883    0.888861   11.778142
min      0.000000     3.0    0.420000    0.000000    0.000000    0.000000
25%      0.000000     3.0   18.000000    0.000000    0.000000    7.750000
50%      0.000000     3.0   24.000000    0.000000    0.000000    8.050000
75%      0.000000     3.0   32.000000    1.000000    0.000000   15.500000
max      1.000000     3.0   74.000000    8.000000    6.000000   69.550000

### Q19.  titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 중복 칼럼으로 고려할 수 있는 컬럼들(6개 내외)을 삭제한 후 나머지 컬럼들로 구성되는 데이터프레임을 df1 이름으로 저장 후 출력하세요. 
2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요. 
4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요. 
5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

In [53]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [54]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [55]:
df1 = df[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck']]
df1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [56]:
#df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
df1.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [57]:
df2 = df1.drop('deck',axis=1)
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [58]:
#df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요.
df2.age.isnull().sum()

177

In [59]:
df2.age.fillna(df2.age.mean(),inplace=True)

In [60]:
df2.age.isnull().sum()

0

In [61]:
#df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요.
df2.embarked.isnull().sum()

2

In [62]:
df2.embarked.fillna(method='ffill',inplace=True)
df2.embarked.isnull().sum()

0

In [ ]:
#df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

### Q20. 보스톤 주택가격 데이터를 탐색한 후 가장 중요한 독립변수 2개를 선정하고 그 이유를 시각화하여 설명하세요.

In [ ]:
from sklearn.datasets import load_boston
# boston 데이타셋 로드
boston = load_boston()

# boston 데이타셋 DataFrame 변환 
bostonDF = pd.DataFrame(boston.data , columns = boston.feature_names)

# boston dataset의 target array는 주택 가격임. 이를 PRICE 컬럼으로 DataFrame에 추가함. 
bostonDF['PRICE'] = boston.target
print('Boston 데이타셋 크기 :',bostonDF.shape)
bostonDF.head()