##  random 모듈

[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [8]:
# [Python random 함수]
import random
print(random.random(),'\n')  # 0.0 <= x < 1.0 사이 랜덤 숫자 리턴
print(random.randint(1,10),'\n') # 1 <= x <= 10 사이의 정수중에서 랜덤 숫자 리턴
print(random.uniform(10,20),'\n') # 10 <= x < 20 min, max 사이 랜덤 실수float 리턴
print(random.randrange(10),'\n') # 지정 범위 정수int 리턴 range(start, stop, step) 
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소중 하나를 랜덤하게 리턴

li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴, 랜덤하게 여러개 요소를 리턴

random.shuffle(li) # 리스트 요소를 랜덤하게 바꿔서 리턴
print(li)


0.43569695537484754 

9 

10.808806840922685 

4 

5 

[1, 3, 5] 

[1, 2, 3, 5, 4]


In [13]:
import numpy as np
r = np.random.rand(6) # 0 ~ 1 사이의 균일분포 n개 리턴
print(r)
r.mean()

[0.28405939 0.5596481  0.64840794 0.90820183 0.91740296 0.42618793]


0.6239846943475841

In [15]:
r = np.random.rand(3,2)
print(r)

[[0.62878026 0.88940752]
 [0.50260493 0.28853099]
 [0.960278   0.79180391]]


In [20]:
# 표준 정규분포
r = np.random.randn(10000) # 평균0, 표준편차1의 표준정규분포 랜덤값 리턴
print(r)
r.mean()

[-2.36371831  0.87786405  0.05587937 ... -1.44508904  0.08751418
 -0.70904963]


-0.004800522990744399

In [21]:
r = np.random.randn(3,2)
print(r)

[[ 0.29346328  0.40878205]
 [-0.85854465  3.13907842]
 [ 0.82762906  0.59169822]]


In [23]:
np.random.uniform(1.0,2.0,10)

array([1.09825855, 1.22641844, 1.65565581, 1.9705612 , 1.45112595,
       1.77412686, 1.09999548, 1.2295434 , 1.09130277, 1.3078254 ])

In [24]:
np.random.uniform(0,1,(2,3))

array([[0.49371126, 0.68140907, 0.71109094],
       [0.86939542, 0.12181013, 0.16043675]])

In [25]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.68547895, 0.35702531, 0.40492716],
       [0.68889227, 0.99203128, 0.68940035]])

In [26]:
import pandas as pd
ar = np.random.rand(4,8) # 0 ~ 1 의 균일분포 표준정규분포 난수를 반환
ar

array([[0.29030593, 0.80126116, 0.94549547, 0.6213129 , 0.42969755,
        0.46600409, 0.43565828, 0.65247778],
       [0.98947513, 0.37481248, 0.15146338, 0.51323404, 0.74312743,
        0.92260555, 0.31324676, 0.03764819],
       [0.87144673, 0.74838088, 0.04179315, 0.17083382, 0.27778844,
        0.19871599, 0.89721841, 0.93405799],
       [0.99553294, 0.95771243, 0.09481273, 0.45686037, 0.53960479,
        0.86390832, 0.4772182 , 0.90845488]])

In [72]:
# 배열을 df로 변환
# columns 8개에 대한 이름

df = pd.DataFrame(ar, columns = ['id','gender','age','region','product','price','qty','time'] )
df

id    gender       age    region   product     price       qty  \
0  0.290306  0.801261  0.945495  0.621313  0.429698  0.466004  0.435658   
1  0.989475  0.374812  0.151463  0.513234  0.743127  0.922606  0.313247   
2  0.871447  0.748381  0.041793  0.170834  0.277788  0.198716  0.897218   
3  0.995533  0.957712  0.094813  0.456860  0.539605  0.863908  0.477218   

       time  
0  0.652478  
1  0.037648  
2  0.934058  
3  0.908455

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df3을 출력하세요.

In [73]:
df['id']=np.random.randint(10,99,4)
df

id    gender       age    region   product     price       qty      time
0  50  0.801261  0.945495  0.621313  0.429698  0.466004  0.435658  0.652478
1  30  0.374812  0.151463  0.513234  0.743127  0.922606  0.313247  0.037648
2  15  0.748381  0.041793  0.170834  0.277788  0.198716  0.897218  0.934058
3  24  0.957712  0.094813  0.456860  0.539605  0.863908  0.477218  0.908455

In [74]:
df.gender = np.random.choice(['male','female'],4)
df

id  gender       age    region   product     price       qty      time
0  50    male  0.945495  0.621313  0.429698  0.466004  0.435658  0.652478
1  30  female  0.151463  0.513234  0.743127  0.922606  0.313247  0.037648
2  15  female  0.041793  0.170834  0.277788  0.198716  0.897218  0.934058
3  24    male  0.094813  0.456860  0.539605  0.863908  0.477218  0.908455

In [112]:
df['gender']=np.random.randint(0,2,4)
df

id  gender       age    region   product     price       qty      time
0  50       0  0.945495  0.621313  0.429698  0.466004  0.435658  0.652478
1  30       0  0.151463  0.513234  0.743127  0.922606  0.313247  0.037648
2  15       0  0.041793  0.170834  0.277788  0.198716  0.897218  0.934058
3  24       1  0.094813  0.456860  0.539605  0.863908  0.477218  0.908455

In [69]:
df['age']=np.random.randint(1,100,4)
df

id  gender  age    region   product     price       qty      time
0  0.290306       0   39  0.621313  0.429698  0.466004  0.435658  0.652478
1  0.989475       0   58  0.513234  0.743127  0.922606  0.313247  0.037648
2  0.871447       0   72  0.170834  0.277788  0.198716  0.897218  0.934058
3  0.995533       0   27  0.456860  0.539605  0.863908  0.477218  0.908455

In [76]:
df3 = df[['id','gender','age']]
df3

id  gender       age
0  50       0  0.945495
1  30       0  0.151463
2  15       0  0.041793
3  24       0  0.094813

## 집합 함수

In [80]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
# 0에 가까운 값을 반환한다.
large_ar = np.random.randn(1000)
large_ar.sort()
large_ar[int(0.5*len(large_ar))]

0.02456044691358048

In [82]:
# np.unique(x) : 배열 내 중복된 원소 제거 후 유일한 원소를 정렬하여 반환
# 배열 집합 연산 
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [83]:
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [85]:
# in1d(x, y) : 첫번째 배열 x가 두번째 배열 y의 원소를 포함하고 있는지 여부의 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,5])

array([False, False, False,  True,  True,  True, False])

## 배열 데이터의 입출력

In [84]:
# np.save() : 1개의 배열을 NumPy format의 바이너리 파일로 저장하기
ar = np.arange(10)
np.save('some_ar',ar)

In [86]:
# np.load() : np.save()로 저장된 *.npy 파일을 배열로 불러오기
np.load('some_ar.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
# np.savez() : 여러개의 배열을 1개의 압축되지 않은 *.npz 포맷 파일로 저장하기
np.savez('ar_archive.npz',a=ar,b=ar)

In [91]:
# np.savez()로 저장된 *.npz 파일을 배열로 불러오기
arch = np.load('ar_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 배열 정렬

In [94]:
a = np.arange(1,10)
print(a)
# np.argsort(a) : np.argsort() 로 index를 받아서 indexing 해오기

[1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [95]:
# 인덱스 배열을 역순으로 출력 
# [시작 인덱스 : 끝 인덱스 : step]
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

## 도전과제(7/6)

In [237]:
# np.arange(336)reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
a = np.arange(336).reshape(6,7,8)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [239]:
np.where(a==a[100])

IndexError: index 100 is out of bounds for axis 0 with size 6

In [236]:
print(a.tolist().index(100))

ValueError: 100 is not in list

In [ ]:
# np.arange(4)을 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# diag(a,k) : 대각 행렬

In [230]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 역행렬

In [101]:
# Q. 0 ~ 10 정수 (5,5) 행렬의 역행렬을 구하세요.
arr = np.random.randint(0,10,size=(5,5))
arr

array([[8, 0, 0, 7, 2],
       [6, 7, 9, 6, 2],
       [9, 7, 9, 5, 8],
       [8, 4, 9, 0, 9],
       [7, 6, 7, 4, 0]])

In [102]:
arr2 = np.linalg.inv(arr)
arr2

array([[ 0.05431781, -0.20198858, -0.00865402,  0.04050819,  0.21874425],
       [-0.16332167, -0.33842755,  0.45313939, -0.29129074,  0.22703001],
       [ 0.03737802,  0.35591972, -0.35849751,  0.23126496, -0.15116921],
       [ 0.08451482,  0.23826183, -0.03719389, -0.03866691, -0.20880133],
       [-0.0130731 , -0.02596207,  0.1647947 , -0.02669858, -0.14417234]])

In [104]:
np.dot(arr, arr2)

array([[ 1.00000000e+00,  3.40005801e-16, -4.44089210e-16,
         1.80411242e-16,  5.55111512e-17],
       [ 3.46944695e-18,  1.00000000e+00,  3.33066907e-16,
         1.38777878e-17,  2.22044605e-16],
       [-5.55111512e-17, -5.55111512e-17,  1.00000000e+00,
         5.55111512e-17,  2.22044605e-16],
       [ 8.50014503e-17,  3.78169718e-16, -2.77555756e-16,
         1.00000000e+00,  2.49800181e-16],
       [ 0.00000000e+00,  1.11022302e-16,  3.33066907e-16,
         2.22044605e-16,  1.00000000e+00]])

## 과제(7/6)
아래 가이드에 따라서 고객 고객별 연간 구매데이터를 생성하고 아래사항을 수행하세요(관측치 1000개)

거래 번호
- id : 1 ~ 1000번 일련번호 - 개시 후 1만 건의 거래가 있었고 걍 거기에 넘버링한 거라고 이해해보자

고객별 속성 데이터
- cusno : 고객번호 1000개 랜덤
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터
- day : 요일
- date : 2020-01-01 ~ 2021-12-31 사이의 날짜 1000개 생성

- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성 (20년도)
- price_21 : 1000 ~ 50000 사이 실수 난수 생성 (21년도)
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성

- time_20 : 01 ~ 24 사이 정수 난수 생성
- time_21 : 01 ~ 24 사이 정수 난수 생성

- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21
- sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0

Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

In [59]:
import numpy as np
import pandas as pd
ar = np.random.rand(1000,4)
df1 = pd.DataFrame(ar, columns = ['id','gender','age','region'] )
ar2 = np.random.rand(1000,6)
df2 = pd.DataFrame(ar2, columns = ['product_20','product_21','price_20','price_21','quantity_20','quantity_21'])
df2.head()

product_20  product_21  price_20  price_21  quantity_20  quantity_21
0    0.874228    0.097154  0.571503  0.498037     0.732354     0.796368
1    0.147480    0.574656  0.589889  0.684665     0.872673     0.441806
2    0.687378    0.889206  0.248924  0.870012     0.628733     0.624532
3    0.031540    0.189709  0.471885  0.613204     0.764566     0.946750
4    0.778186    0.425801  0.032392  0.728733     0.815517     0.751901

In [60]:
# df1['id']=np.random.randint(1,1001,1000)
df1['id'] = np.arange(1,1001)
df1['gender']=np.random.randint(0,2,1000)
df1['age']=np.random.randint(0,81,1000)
df1['region']=np.random.randint(1,11,1000)
df1['cusno']=np.arange(1,1001)
#li = list(range(1,1001))
#df1['cusno']= random.sample(li,1000)

df1.head()

id  gender  age  region  cusno
0   1       0   32       3      1
1   2       0   51       3      2
2   3       0   49       4      3
3   4       0   30       1      4
4   5       0   53       1      5

In [61]:
df2['product_20']=np.random.choice([10,20,30],1000)
df2['product_21']=np.random.choice([10,20,30],1000)
df2['price_20']=np.random.uniform(1000,50001,1000)
df2['price_21']=np.random.uniform(1000,50001,1000)
df2['quantity_20']=np.random.randint(1,101,1000)
df2['quantity_21']=np.random.randint(1,101,1000)
df2.head()

product_20  product_21      price_20      price_21  quantity_20  \
0          30          20   8805.444334  45264.321637           74   
1          30          30  22636.329117  37113.754946           33   
2          10          10  32943.275707   5829.994285           11   
3          20          20  20033.342530  36404.958761           35   
4          20          20  15723.303533   5067.767481           64   

   quantity_21  
0           85  
1            2  
2           18  
3           78  
4           43

In [62]:
df = df1.join(df2,how='outer')
#df.set_index('id',inplace=True)
df.head()

id  gender  age  region  cusno  product_20  product_21      price_20  \
0   1       0   32       3      1          30          20   8805.444334   
1   2       0   51       3      2          30          30  22636.329117   
2   3       0   49       4      3          10          10  32943.275707   
3   4       0   30       1      4          20          20  20033.342530   
4   5       0   53       1      5          20          20  15723.303533   

       price_21  quantity_20  quantity_21  
0  45264.321637           74           85  
1  37113.754946           33            2  
2   5829.994285           11           18  
3  36404.958761           35           78  
4   5067.767481           64           43

In [63]:
df['price_20']= round(df['price_20'],2)
df['price_21']= round(df['price_21'],2)
df.head()

id  gender  age  region  cusno  product_20  product_21  price_20  price_21  \
0   1       0   32       3      1          30          20   8805.44  45264.32   
1   2       0   51       3      2          30          30  22636.33  37113.75   
2   3       0   49       4      3          10          10  32943.28   5829.99   
3   4       0   30       1      4          20          20  20033.34  36404.96   
4   5       0   53       1      5          20          20  15723.30   5067.77   

   quantity_20  quantity_21  
0           74           85  
1           33            2  
2           11           18  
3           35           78  
4           64           43

In [64]:
df['amount_20']=df['price_20']*df['quantity_20']
df['amount_21']=df['price_21']*df['quantity_21']
df.head()

id  gender  age  region  cusno  product_20  product_21  price_20  price_21  \
0   1       0   32       3      1          30          20   8805.44  45264.32   
1   2       0   51       3      2          30          30  22636.33  37113.75   
2   3       0   49       4      3          10          10  32943.28   5829.99   
3   4       0   30       1      4          20          20  20033.34  36404.96   
4   5       0   53       1      5          20          20  15723.30   5067.77   

   quantity_20  quantity_21   amount_20   amount_21  
0           74           85   651602.56  3847467.20  
1           33            2   746998.89    74227.50  
2           11           18   362376.08   104939.82  
3           35           78   701166.90  2839586.88  
4           64           43  1006291.20   217914.11

In [19]:
#df1['sales'] = np.where(df1.amount_20 <= df1.amount21,1,0)

In [65]:
df['sales'] = df['amount_21']-df['amount_20']
df.head()

id  gender  age  region  cusno  product_20  product_21  price_20  price_21  \
0   1       0   32       3      1          30          20   8805.44  45264.32   
1   2       0   51       3      2          30          30  22636.33  37113.75   
2   3       0   49       4      3          10          10  32943.28   5829.99   
3   4       0   30       1      4          20          20  20033.34  36404.96   
4   5       0   53       1      5          20          20  15723.30   5067.77   

   quantity_20  quantity_21   amount_20   amount_21       sales  
0           74           85   651602.56  3847467.20  3195864.64  
1           33            2   746998.89    74227.50  -672771.39  
2           11           18   362376.08   104939.82  -257436.26  
3           35           78   701166.90  2839586.88  2138419.98  
4           64           43  1006291.20   217914.11  -788377.09

In [66]:
df['sales']=df.sales.apply(lambda x:1 if x > 0 else 0)
df.head()

id  gender  age  region  cusno  product_20  product_21  price_20  price_21  \
0   1       0   32       3      1          30          20   8805.44  45264.32   
1   2       0   51       3      2          30          30  22636.33  37113.75   
2   3       0   49       4      3          10          10  32943.28   5829.99   
3   4       0   30       1      4          20          20  20033.34  36404.96   
4   5       0   53       1      5          20          20  15723.30   5067.77   

   quantity_20  quantity_21   amount_20   amount_21  sales  
0           74           85   651602.56  3847467.20      1  
1           33            2   746998.89    74227.50      0  
2           11           18   362376.08   104939.82      0  
3           35           78   701166.90  2839586.88      1  
4           64           43  1006291.20   217914.11      0

In [11]:
compare = df['amount_20'] < df['amount_21']
df['sales']=compare
df.head()

id  gender  age  region  cusno  product_20  product_21  price_20  price_21  \
0   1       0   55       6      1          30          20  28057.55  35524.49   
1   2       0   60       9      2          20          20  27963.36  15614.74   
2   3       0   31       9      3          10          10  25805.02  45371.92   
3   4       0   50       1      4          30          20  27571.10   4591.58   
4   5       1   17       5      5          30          20   5100.91  15333.16   

   quantity_20  quantity_21   amount_20   amount_21  sales  
0           80           17  2244604.00   603916.33  False  
1           65           69  1817618.40  1077417.06  False  
2           79           33  2038596.58  1497273.36  False  
3           66           35  1819692.60   160705.30  False  
4           89           50   453980.99   766658.00   True

In [228]:
def tf(x):
    if x == True:
        return 0
    else:
        return 1

In [229]:
df['sales']=df['sales'].apply(lambda x :tf(x))
df.head()

id  gender  age  region  cusno  product_20  product_21  price_20  \
0  869       0   69       8    682          20          10  36085.79   
1   56       0   70       1    565          20          20  33818.64   
2  320       0    6       9    822          10          20  12600.31   
3  193       0   46       7    616          30          20  40314.45   
4  502       1   69       8    359          20          30  44808.55   

   price_21  quantity_20  quantity_21   amount_20   amount_21  sales  
0  45055.84           18           35   649544.22  1576954.40      0  
1   9030.18            6           27   202911.84   243814.86      0  
2  25537.02           44           81   554413.64  2068498.62      0  
3  29175.50           71           89  2862325.95  2596619.50      1  
4  39927.71           82           40  3674301.10  1597108.40      1

Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요

Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.

In [44]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# 구매감소고객
# 고객별 요약데이터

In [ ]:
# 연별  / 분기별  / 전체 매출
# 지역별
# 아이템별(고가,중가,저가)

Q4. 거래일자, 요일, 시간을 추가해서 10000개의 관측치를 갖는 데이터셋을 만드세요.

In [71]:
df[]

id  gender  age  region  cusno  product_20  product_21  price_20  price_21  \
0   1       0   32       3      1          30          20   8805.44  45264.32   
1   2       0   51       3      2          30          30  22636.33  37113.75   
2   3       0   49       4      3          10          10  32943.28   5829.99   
3   4       0   30       1      4          20          20  20033.34  36404.96   
4   5       0   53       1      5          20          20  15723.30   5067.77   

   quantity_20  quantity_21   amount_20   amount_21  sales  
0           74           85   651602.56  3847467.20      1  
1           33            2   746998.89    74227.50      0  
2           11           18   362376.08   104939.82      0  
3           35           78   701166.90  2839586.88      1  
4           64           43  1006291.20   217914.11      0

In [70]:
# 날짜 거래 데이터프레임 만들기

#date
date_list = list(pd.date_range('2020-01-01','2021-12-31',freq='D')
df['date']=np.random.choice(data_list,size=1000)
#day
df['day']=df['date'].apply(lambda x:x.weekday())
df['day']=df['day'].replace(list(range(7)),['MON','TUE', 'WED', 'THU', 'FRI','SAT','SUN'])
#time
df['time']=np.random.randint(1,25,size=1000)

SyntaxError: invalid syntax (2877343236.py, line 5)