## numpy

In [1]:
import numpy as np

- array

In [ ]:
각 차원을 축(axis)이라 한다.
축의 개수는 차원의 개수 ndim
배열의 차원 shape tuple로 표시

In [6]:
np.array([1,2,3,4])   # list를 array함수로 만든다

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

In [7]:
max([1,2,3,4])

4

In [11]:
a.shape    # 결괏값 (4,) = (4)으로 1차원 값 ','무시

(4,)

In [12]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [24]:
a= np.array([[1,2],[3,4]])

In [25]:
a.shape         # 2차원

(2, 2)

In [17]:
a= np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
a.shape

(2, 3)

In [26]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
a.shape    # 3차원

(2, 2, 2)

In [28]:
a = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,7]]])
a

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 7]]])

In [39]:
a.shape       # (z,y,x)  열:y 행:x

(2, 2, 3)

- arange

In [37]:
np.arange(10)   # numpy: a+range  # array type으로 출력

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- reshape

In [40]:
np.arange(10).reshape(2,5)   # reshape(2,5) 2행 5열로 재배열한다.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
np.arange(24).reshape(2,3,4)  # reshape(2,3,4) 3행 4열 2장 만들기

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [52]:
np.arange(36).reshape(3,4,3)   #reshape(3,4,3) 4행 3열 3장

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

- 배열의 연산

In [ ]:
# numpy 연산은 원소들끼리 묶어진다.
element - wise 끼리끼리
row - wise row 끼리
column - wise column 끼리

In [56]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [54]:
a-b

array([-4, -4, -4, -4])

In [55]:
a*b

array([ 5, 12, 21, 32])

In [61]:
c=np.array([10])   # element 개수를 맞춰 연산
a+c

array([11, 12, 13, 14])

In [60]:
a+b+c

array([16, 18, 20, 22])

In [62]:
li = [1,2,3,4,5,6]
list(map(lambda x: 2*x, li))

[2, 4, 6, 8, 10, 12]

In [64]:
ar = np.array([1,2,3,4,5])
ar*2

array([ 2,  4,  6,  8, 10])

In [66]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

In [68]:
a

array([[1, 2],
       [3, 4]])

In [69]:
b

array([[5, 6],
       [7, 8]])

In [67]:
a+b

array([[ 6,  8],
       [10, 12]])

In [70]:
a*b

array([[ 5, 12],
       [21, 32]])

In [72]:
# 행렬의 곱셈
a@b

array([[19, 22],
       [43, 50]])

In [73]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [74]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
내적 곱셈 inner product / dot product (실수)
외적 곱셈 out product - (벡터)

In [78]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
np.ones((3,3),int)   #data type

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [194]:
np.identity(4) #정사각행렬

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- 바꾸기

In [80]:
a

array([[1, 2],
       [3, 4]])

In [81]:
a.T

array([[1, 3],
       [2, 4]])

- 비교하기

In [83]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

In [84]:
a > b

array([False, False,  True,  True])

In [85]:
a > 3

array([False, False, False,  True])

In [86]:
a[a>2]

array([3, 4])

- 정렬하기

In [ ]:
1차원 배열의 정렬,역순으로 정렬
2차원 배열의 정렬과 축기준으로 정렬

In [87]:
a = np.array([3,4,2,1,6,5])
a

array([3, 4, 2, 1, 6, 5])

In [88]:
a = np.sort(a)
a

array([1, 2, 3, 4, 5, 6])

In [89]:
a.sort()

In [90]:
a

array([1, 2, 3, 4, 5, 6])

In [91]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [201]:
# 축을 지정하여 정렬
a = np.array([[2,1,6],[0,7,4],[5,13,2]])
a

array([[ 2,  1,  6],
       [ 0,  7,  4],
       [ 5, 13,  2]])

In [199]:
np.sort(a,axis=0)   #열로 지정하여 정렬 row - wise

array([[ 0,  1,  2],
       [ 2,  7,  4],
       [ 5, 13,  6]])

In [200]:
np.sort(a,axis=1)  #coloumn = wise

array([[ 1,  2,  6],
       [ 0,  4,  7],
       [ 2,  5, 13]])

In [100]:
a

array([[ 2,  1,  6],
       [ 0,  7,  4],
       [ 5, 13,  2]])

In [102]:
a[1,2]=14
a

array([[ 2,  1,  6],
       [ 0,  7, 14],
       [ 5, 13,  2]])

In [104]:
a = np.ones((2,2),int)
a

array([[1, 1],
       [1, 1]])

In [105]:
a = np.ones((2,2),int)*7
a

array([[7, 7],
       [7, 7]])

In [195]:
np.full((2,2),7)  #7로 채우다

array([[7, 7],
       [7, 7]])

In [114]:
#예제1
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [115]:
yellow=a[4:]
yellow

array([[20, 21, 22, 23, 24]])

In [132]:
a[1,0],a[1,2],a[3,0],a[3,2]

(5, 7, 15, 17)

In [129]:
a[ :, 1: :2 ]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [131]:
a[1::2, 0:3:2]

array([[ 5,  7],
       [15, 17]])

- indexing

In [211]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [213]:
a[0]=10
a

array([10,  1,  2,  3])

In [214]:
a = np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [215]:
a.ndim

2

In [216]:
a.shape

(2, 4)

In [217]:
a.size

8

In [219]:
a[1,3]=-1 # 1 = row 3 = column

In [220]:
a[1]

array([10, 11, 12, -1])

In [221]:
a[1,]

array([10, 11, 12, -1])

In [222]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [223]:
a[:1]

array([[0, 1, 2, 3]])

- slicing

In [225]:
a=np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

In [226]:
a[1:3]

array([11, 12])

In [227]:
a[1:-2]

array([11, 12])

In [229]:
a[-4:3]

array([11, 12])

In [228]:
a[-2:1]

array([], dtype=int32)

In [230]:
a=np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

In [231]:
a[:3]

array([10, 11, 12])

In [232]:
a[-2:]

array([13, 14])

In [233]:
a[::2]

array([10, 12, 14])

- boolean indexing

In [135]:
a = np.array([0,10,20,30,40,50,60,70])
mask = np.array([0,1,1,0,0,1,0,0],bool)
mask

array([False,  True,  True, False, False,  True, False, False])

In [137]:
# True만 뽑아서 보여준다.
a[mask]

array([10, 20, 50])

In [138]:
a > 40

array([False, False, False, False, False,  True,  True,  True])

In [139]:
a[ a > 40]

array([50, 60, 70])

In [141]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- Fancy indexing

In [154]:
# 행, 열 index (0,1)(1,2)(2,0)(2,3)
a[[0,1,2,2],[1,2,0,3]]

array([ 1,  7, 10, 13])

In [148]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [153]:
#(0,1)(1,2)(2,3)(3,4)
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

- Broadcasting

- functions

In [159]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
np.sum(a)

21

In [166]:
np.sum(a,axis=0) #열을 축으로 sum

array([5, 7, 9])

In [165]:
np.sum(a,axis=1)  #행을 축으로 sum

array([ 6, 15])

In [167]:
np.min(a)

1

In [168]:
np.min(a,axis=0)

array([1, 2, 3])

In [169]:
np.min(a,axis=1)

array([1, 4])

In [170]:
np.max(a)

6

In [172]:
np.max(a,axis=0)

array([4, 5, 6])

In [171]:
np.max(a,axis=1)

array([3, 6])

In [177]:
np.argmin(a) # 최소값(1)이 나오는 index번호

0

In [178]:
np.argmax(a) # 최대값(6)이 나오는 index번호

5

- where

In [181]:
a = np.array([6,8,7,9,10],int)

In [187]:
np.where(a>7) #return index 참, 거짓이 아닌 조건에 맞는 index번호를 return한다.

(array([], dtype=int64), array([], dtype=int64))

In [185]:
index = np.where(a>7)
print(index) #index
a[index] #value

(array([1, 3, 4], dtype=int64),)


array([ 8,  9, 10])

In [186]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [189]:
np.where(a > 4)    #[1,1]->5 [1,2]->6

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [192]:
a[np.where(a > 4)] # index값을 구할 때 용이하다

array([5, 6])

## Series
- 객체를 담을 수 있는 1차원 자료구조

In [1]:
import pandas as pd

In [19]:
pd.Series(["a","b","c"])     #왼쪽에 index(색인)를 보여주고 오른쪽에 해당 값을 보여준다.

0    a
1    b
2    c
dtype: object

In [18]:
s = pd.Series(["a","b","c"]) 

In [8]:
s

0    a
1    b
2    c
dtype: object

In [ ]:
# object => Pandas에서 string을 의미한다.

In [9]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
s.values

array(['a', 'b', 'c'], dtype=object)

In [15]:
sdata = {"Ohio":35000,"Texas":71000}
s1 = pd.Series(sdata)

In [16]:
type(s1)

pandas.core.series.Series

In [22]:
s1

Ohio     35000
Texas    71000
dtype: int64

In [21]:
s1.index

Index(['Ohio', 'Texas'], dtype='object')

In [23]:
s1["Ohio"]

35000

## DataFrame
- 표 같은 2차원 자료구조

In [26]:
pd.DataFrame([[1,2],[3,4]])

0  1
0  1  2
1  3  4

In [28]:
pd.DataFrame([[1,2],[3,4]], index = ["a","b"])

0  1
a  1  2
b  3  4

In [32]:
# 리스트에서 만들기
pd.DataFrame([[1,2],[3,4]], index = ["a","b"],columns=["A","B"])

A  B
a  1  2
b  3  4

In [38]:
# 딕셔너리에서 만들기
pd.DataFrame({"A":[1,3], "B":[2,4]})

A  B
0  1  2
1  3  4

In [39]:
# 딕셔너리에서 만들 때는 a가 Calumn으로 가고 index만 추가해주면 된다.
pd.DataFrame({"A":[1,3], "B":[2,4]},index = ["a","b"])

A  B
a  1  2
b  3  4